### PR TITLE
DM-33220: Change Task metadata storage class to TaskMetadata

### PR DESCRIPTION
**Pull request by timj**
This is now the standard storage class for task metadata.

{Summary of changes. Prefix PR title with ticket handle.}

****

- [x] Passes Jenkins CI.
- [ ] Documentation is up-to-date.

Preview the docs at: https://pipelines.lsst.io/v/DM-FIXME

### CODE REVIEW

**Review by kfindeisen — COMMENTED** [review]
I realize we have a deadline of this evening, but would it be possible to propagate this change to the documentation? I know that at least the docstrings in the same file still refer to metadata as being a `PropertySet`.

**Comment by timj** [comment]
Yes. Sorry. Didn't realize.

**Comment by kfindeisen** [comment]
[A search](https://github.com/lsst/verify/search?q=PropertySet) reveals only three files that mention `PropertySet`, this file and two related test files. I'd suggest replacing all references; it should be safe.

**Comment by timj** [comment]
Done. Tests pass locally.

**Review by kfindeisen — APPROVED** [review]
Looks good, thanks for the changes!

**Pull request merged**
